[package]
name = "abav1"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2021"
description = "AV1 re-encoding"
repository = "https://github.com/alexheretic/ab-glyph"
keywords = ["av1", "vmaf"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }
ffprobe = "0.3"
anyhow = "1.0.53"
tokio = { version = "1.15", features = ["rt", "macros", "process", "fs", "signal"] }
tokio-stream = { version = "0.1" }
tokio-process-stream = { git = "https://github.com/alexheretic/tokio-process-stream", branch = "chunk" }
indicatif = "0.16.2"
console = "0.15"
once_cell = "1.9"
futures = "0.3.19"
time = { version = "0.3", features = ["parsing", "macros"] }

[profile.release]
lto = true
opt-level = "s"
